blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.BlogPost.as_view(), name='home'),
    path('post_like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('post_detail/<slug:slug>', views.PostDetail.as_view(), name='post_detail'),
    path('add_post/', views.AddPostView.as_view(), name='add_post'),
    path('edit_post/<slug:slug>', views.EditPostView.as_view(), name='edit_post'),
    path('delete_post/<slug:slug>', views.DeletePostView.as_view(), name='delete_post'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),
]

travelblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/',  include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify


STATUS = ((0, "Draft"), (1, "Published"))


class BlogPost(models.Model):

    title = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=130, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="BlogPost"
    )
    updated_on = models.DateTimeField(auto_now=True)
    published_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    spotlight_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    date_time = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blog_likes', blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

class Meta:
    ordering = ['-published_on']


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=60)
    email = models.EmailField()
    published_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    body = models.TextField()

    class Meta:
        ordering = ['-published_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    facebook = models.CharField(max_length=300, blank=True, null=True)
    instagram = models.CharField(max_length=300, blank=True, null=True)
    linkedin = models.CharField(max_length=300, blank=True, null=True)
    
    def __str__(self):
        return str(self.user)

templates/add_post.html
{% extends "base.html" %}


{% block content %}

<center>
<h1>Add Blog Post</h1>
</center>

    <br/><br/>

<div class="container">
        <div class="row">
            <div class="col-md-8 mt-3 offset-md-2">

        <strong>
            <div class="col text-center">
                <div class="form-group">
                    <form class = "d-inline" action="{% url 'add_post' %}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p}}

                        <button class="btn btn-outline-primary" type="Submit">Post it!</button>
                        <br>
                    </form>
                </div>
            </div>


    </strong>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="h-100">

<head>
    <title>Asian Travel</title>

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/new.style.css' %}">

</head>
<body class="d-flex flex-column h-100 main-bg">
        <!-- Navigation -->

        <nav class="navbar navbar-expand-sm bg-light justify-content-center">
            <div class="container-fluid">
                    <img src="https://res.cloudinary.com/vannesha/image/upload/v1658436392/static/css/images/logo.91d58736aa92.png" alt="logo">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class = "navbar-nav position-absolute end-0 mx-6">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'add_post' %}">Add Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                        {{ message | safe }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>


        <main class="flex-shrink-0 main-bg">
            {% block content %}
            <!-- Content Goes here -->
            {% endblock content %}
        </main>

        <!-- Footer -->
        <footer class="footer mt-auto py-4 dark-bg">
            <p class="m-0 text-center text-black bold">Join the adventures!</p>
            <p class="m-0 text-center text-black">Follow us: 
                <a href="https://facebook.com/"><i class="fab fa-facebook-square ms-3"></i>
                <a href="https://twitter.com/"><i class="fab fa-twitter-square ms-3"></i></a>
                <a href="https://www.instagram.com/"><i class="fab fa-instagram-square ms-3"></i>
                <a href="https://www.youtube.com/"><i class="fab fa-youtube-square ms-3"></i>
        </footer>
        <script>
            setTimeout(function () {
                let messages = document.getElementById('msg');
                let alert = new bootstrap.Alert(messages);
                alert.close();
            }, 2000);
        </script>
    </body>

</html>

templates/delete_post.html
{% extends "base.html" %}

{% block content %}
<div class="masthead.delete">
    <div class="container">
            <div class="row g-0">
                <div class = "col-md-4"></div>
                    <div class="col-md-3 masthead-text">
                <strong>
                    <br/><br/>
                        <div class="form-group">
                            <form class = "d-inline" action="{% url 'delete_post' blog %}" method="POST">
                                {% csrf_token %}
                                <h1 class="edit" id="edit">Are you sure?</h1> 
                                <br>
                                <button class="btn btn-secondary">Delete Post</button>
                            </form>
                        </div>
                </strong>        
            </div>     
        </div>
    </div>
</div>


{% endblock %}

templates/edit_post.html
{% extends "base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Edited Post" %}{% endblock %}

{% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class = "col-md-4"></div>
                <div class="col-md-3 masthead-text">
                <strong>
                    <br/><br/>
                    <h1 class="edit" id="edit">Edit Post</h1> 
                    <br/><br/>
                        <div class="form-group"></div>
                            <form class = "d-inline" action="{% url 'edit_post' blog %}" method="POST">
                                {% csrf_token %}
                                {% if redirect_field_value %}
                                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                                {% endif %}
                                {{ form.as_p}}
                                
                                <button class="btn btn-secondary">Edit Post</button>
                            </form>
                        </div>
                </strong>         
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Profile" %}{% endblock %}

{% block content %}
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class = "col-md-4"></div>
                    <strong>
                        <br/><br/>
                        <div class="col text-center">
                            <h1 class="edit" id="edit">Edit Profile</h1> 
                            <br>
                            <div class="form-group">
                                <form class = "d-inline" action="{% url 'edit_profile' %}" method="POST">
                                    {% csrf_token %}
                                    {{ form.as_p}}
                                    {% if redirect_field_value %}
                                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                                    {% endif %}
                                    <button class="btn btn-outline-secondary" type="Submit">{% trans "Edit Profile" %}</button>
                                </form>
                            </div>
                        </div>
                    </strong>
                </div>      
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">

        <!-- Blog Entries Column -->
        <div class="row d-flex justify-content-center">
            <div class="row">
                {% for post in blogpost_list %}
                <div class="col-md-12">
                        <div class="card-body">
                        <a href="{% url 'post_detail' post.slug  %}" class="post-link">
                            <h2 class="card-title">{{ post.title }}</h2>
                            <p class="card-text">{{ post.excerpt }}</p>
                        </a>
                        <hr />
                        <p class="card-text">{{ post.published_on}} <i class="far fa-heart"></i>
                                {{ post.number_of_likes }}</p>
                </div>
                    {% if forloop.counter|divisibleby:3%}
                    <div class="row">
                    {% endif %}
                    {% endfor %}
                    </div>
            </div>  
        </div>
    </div>

    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-15">
            <div class="col-md-12 masthead-text">
                <h1 class="post-title">{{ post.title }}</h1>
                <p class="post-subtitle">{{ post.author }} | {{ post.published_on }}</p>
                {% if request.user == post.author %}
                    <div>
                        <button class="btn btn-outline-secondary" data-toggle="buttons" type="Submit">
                        <a href="{% url 'edit_post' post.slug %}">Edit Post</a>
                        
                        <button class="btn btn-outline-secondary" type="Submit">
                        <a href="{% url 'delete_post' post.slug %}">Delete Post</a>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col card mb-4  mt-3 left  top">
            <div class="card-body">
                <p class="card-text ">
                    {{ post.content | safe }}
                </p>
                <div class="row">
                    <div class="col-2">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class = "d-inline" action="{% url 'post_like' post.slug %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}

                                <button type="submit" class="btn btn-outline-secondary" name= "blogpost_id" value="{{post.slug}}" class="btn-like"><i
                                    class="fas fa-heart"></i></button>

                                {% else %}

                                <button type="submit" class="btn btn-outline-secondary" name= "blogpost_id" value="{{post.slug}}" class="btn-like"><i
                                    class="far fa-heart"></i></button>
                                    

                                {% endif %}
                            </form>
                            {% else %}
                            <span class = "text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <span class="text-secondary"> {{ post.number_of_likes }}</span>
                        </strong>

                        
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            {{ total_comments }}</strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 ">
            <h3>Comments:</h3>
            <div class="card-body">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <p>Posting as: {{ user.username }}</p>
                <form method="post" style="margin-top: 1.3em;">
                    {{ comment_form | crispy }}
                    {% csrf_token %}
                    <br>
                    <button type="submit" class="btn btn-outline-secondary">Submit</button>
                </form>
                {% endif %}
                {% endif %}
                
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}

<div class="container profile">
    <div class="row g-0">
        <div class = "col-md-4"></div>
            <div class="col-md-3 masthead-text">
        <h1 class="edit" id="edit">Profile</h1> 
        <div class="col-md-8">
            <div class="profile-tab">
                <div class="tab-pane">
                    <br><br>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Username:</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{user}}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Full Name:</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{user.get_full_name}}</p>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6">
                            <label>Email:</label>
                        </div>
                        <div class="col-md-6">
                            <p>{{user.email}}</p>
                        </div>
                    {% if user.profile.bio %}
                    <div class="row">
                        <div class="col-md-6">
                            <label>Biodata:</label>
                        </div>
                        <div class="col-md-6">
                            <textarea name="Bio" cols="50" rows="10" id="id_bio">{{user.profile.bio}}</textarea>
                        </div>
                    </div>
                    {% endif %}
                    {% if user.profile.linkedin %}
                    <div class="row md">
                        <div class="col-md-6">
                            <label>Linkedin:</label>
                        </div>
                        <div class="col-md-6">
                            <p><a href="{{user.profile.linkedin}}">{{user.profile.linkedin}}</a></p>
                        </div>
                    </div>
                    {% endif %}
                    {% if user.profile.instagram %}
                    <div class="row">
                        <div class="col-md-6">
                            <label>Instagram:</label>
                        </div>
                        <div class="col-md-6">
                            <p><a href="{{user.profile.instagram}}">{{user.profile.instagram}}</a></p>
                        </div>
                    </div>
                    {% endif %}
                    {% if user.profile.facebook %}
                    <div class="row">
                        <div class="col-md-6">
                            <label>Facebook:</label>
                        </div>
                        <div class="col-md-6">
                            <p><a href="{{user.profile.facebook}}">{{user.profile.facebook}}</a></p>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <a href="/edit_profile/" class="btn btn-secondary">Edit Profile</a>
            </div>
        </div>
</div>
</div>

{% endblock %}